In [3]:
import numpy as np

In [7]:
#This is me practicing to run a script on Jupyter notebook on the Polaris supercomputer

print('My name is Aleksandar Dyulgerov')

list = np.array([1,2,3,4,5,6,7,8,9,10]) #numpy array

mask = list > 5 #boolean mask

print(list[mask])

print(list)

list = list[mask]

print(list)

My name is Aleksandar Dyulgerov
[ 6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 6  7  8  9 10]
